version: 2

project_name: cb

before:
  hooks:
    - go mod tidy

builds:
  - id: cb
    main: .
    binary: cb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: cb
    name_template: "cb_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - README.md
      - install.sh

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: zihaolam
    name: codebridge
  draft: false
  prerelease: auto
